### ISSUE TITLE
EvalSum bug

### ISSUE THREAD

**Issue by DarkFrak74** [openfheorg/openfhe-python#169]
Hello, I'm doing some tests with the python wrapper and I noticed a bug(?) with the EvalSum function with batch sizes 1024+.
In the following Euclidean distance, the sum returns wrong results (even negative numbers). Everything works fine with batch sizes 128, 256 and 512.

`   filename_a = "1000_1024_1_a.npy"
    filename_b = "1000_1024_1_b.npy"

    dataset_a = numpy.load(filename_a)
    dataset_b = numpy.load(filename_b)

    v1 = list(dataset_a[0])
    v2 = list(dataset_b[0])

    mult_depth = 1
    scale_mod_size = 50
    batch_size = len(v1)

    parameters = openfhe.CCParamsCKKSRNS()
    parameters.SetMultiplicativeDepth(mult_depth)
    parameters.SetScalingModSize(scale_mod_size)
    parameters.SetBatchSize(batch_size)
    parameters.SetScalingTechnique(ScalingTechnique.FLEXIBLEAUTOEXT)

    cc = openfhe.GenCryptoContext(parameters)
    cc.Enable(openfhe.PKESchemeFeature.PKE)
    cc.Enable(openfhe.PKESchemeFeature.KEYSWITCH)
    cc.Enable(openfhe.PKESchemeFeature.LEVELEDSHE)
    cc.Enable(openfhe.PKESchemeFeature.ADVANCEDSHE)

    keys = cc.KeyGen()
    cc.EvalMultKeyGen(keys.secretKey)
    cc.EvalRotateKeyGen(keys.secretKey, [2 ** n for n in range(0, math.ceil(math.log2(batch_size)) + 1)])

    print("keys generated")

    # Encoding and encryption
    # The operation is performed between encrypted v1 and plaintext v2
    ptx1 = cc.MakeCKKSPackedPlaintext(v1)
    ptx2 = cc.MakeCKKSPackedPlaintext(v2)

    ctx1 = cc.Encrypt(keys.publicKey, ptx1)

    # Component-wise difference: ctx - ptx
    diff_ctx = cc.EvalSub(ctx1, ptx2)

    # Component-wise square: (ctx - ptx)^2
    square_ctx = cc.EvalSquare(diff_ctx)

    # Sum of all the components
    squared_ed_ctx = cc.EvalSum(square_ctx, batch_size)

    res = cc.Decrypt(keys.secretKey, squared_ed_ctx)
    res.SetLength(batch_size)

    value = res.GetRealPackedValue()[0]

    print(f"Plaintext value: {euclidean_distance(v1,v2)}")
    print(f"HE value: {math.sqrt(value)}")`

`
def euclidean_distance(v1, v2):
    v1 = np.array(v1)
    v2 = np.array(v2)

    ed = np.sqrt(np.sum(np.square(v1-v2)))
    return ed`

However, setting multiplicative depth to 2 everything works fine. Does the EvalSum consume a level? Is it supposed to do so?
Files to reproduce the bug are attached.
[1000_1024_1_.zip](https://github.com/user-attachments/files/16869290/1000_1024_1_.zip)

**Comment by yspolyakov** [comment]
This depends on the norm of the input values. If the sum is higher than roughly $2^{60}/2^{50}$ (for your cryptocontext parameters), then you will have an overflow and need an extra RNS limb (level) to support larger numbers. This issue has been discussed/answered multiple times in the Discourse forum. It does not look like a bug to me.

**Comment by DarkFrak74** [comment]
Actually, the inputs are vectors of 1024 randomly generated elements in [-1,1]. Even with the square, the sum could never reach $2^{50}$.

**Comment by yspolyakov** [comment]
See my response at https://openfhe.discourse.group/t/evalsum-possible-bug/1533/4?u=ypolyakov It is not a bug. This behavior is by design.
