### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by juealcs** [openfheorg/openfhe-python#82]
Please guide me to solve this problem. I have followed all the steps to install it but getting this error.
fatal error: openfhe.h: No such file or directory
   10 | #include "openfhe.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/openfhe.dir/build.make:63: CMakeFiles/openfhe.dir/src/lib/bindings.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/openfhe.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by reneroliveira** [comment]
Hi, @juealcs!

Apparently, something went wrong in the installation of openfhe-development. Can you try reinstalling it following the README instructions? If you're using Linux, try installing with sudo, so that the installation goes global and openfhe-python can recognize it

**Comment by IanQS** [comment]
Is this still a problem?

**Comment by IanQS** [comment]
Please include more details. Exactly what commands are you running, what OS, what version of OpenFHE and OpenFHE-python are you installing?

**Comment by yspolyakov** [comment]
Looks to me that the CMake install cannot find openfhe. This means that either "sudo make install" was not used or, alternatively, the custom path to OpenFHE was not specified.

**Comment by yspolyakov** [comment]
This issue affected one of the prior releases and is now fixed.
