### ISSUE TITLE
Segmentation Fault on GenerateLUTViaFunction

### ISSUE THREAD

**Issue by reneroliveira** [openfheorg/openfhe-python#85]
When trying to run FuncViaSchemeSwitching function from scheme-swithing.py example, the code apparently runs fine, but it throws a segmentation fault at the end.
![image](https://github.com/openfheorg/openfhe-python/assets/53785783/2eee2e79-fce8-4b72-9b4a-e66fafc4ada7)

By debugging it, the cause of the problem is at the line:
```python
lut = ccLWE.GenerateLUTviaFunction(fp, pLWE)
```
if i comment the rest of the code after it, segmentation fault still occurs. But if I comment also the above line, no error occurrs!

**Comment by bpradeep508** [comment]
When trying to run  scheme-swithing.py example, it throws a segmentation fault . 
![Screenshot from 2024-02-09 18-27-35](https://github.com/openfheorg/openfhe-python/assets/46367140/cfa3c25e-bcbf-45df-bf6b-6b738d91c0c1)

cc = GenCryptoContext(parameters)

**Comment by yspolyakov** [comment]
These issues have been fixed in #112 All scheme switching examples are now working
