### ISSUE TITLE
Complete BinFHEContext API

### ISSUE THREAD

**Issue by reneroliveira** [openfheorg/openfhe-python#86]
Expose missing methods from [BinFHEContext C++ class](https://openfhe-development.readthedocs.io/en/latest/api/classlbcrypto_1_1BinFHEContext.html#_CPPv4N8lbcrypto13BinFHEContextE)

Start by exposing what is needed to run the examples below, then complete the API with methods not covered by the examples:

 - [Code with JSON serialization](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/boolean-serial-json.cpp)
 - [Code with Binary Serialization](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/boolean-serial-binary.cpp)
 - [Large-Precision Comparison](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/eval-sign.cpp)
 - [Small-Precison Arbitrary Function Evaluation](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/eval-function.cpp)

**Comment by arcturusannamalai** [comment]
@reneroliveira - the links are expired; can you provide details once again ?

**Comment by reneroliveira** [comment]
@arcturusannamalai,

Thanks for pointing it. I just fixed the links!

**Comment by arcturusannamalai** [comment]
one part of problem is fixed; we still need to see if the update API is sufficient to reproduce the examples - for that reason we have to leave this ticket open

**Comment by yspolyakov** [comment]
Thank you @arcturusannamalai Could you add a PR with the actual examples, too:

[Large-Precision Comparison](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/eval-sign.cpp)
[Small-Precison Arbitrary Function Evaluation](https://github.com/openfheorg/openfhe-development/blob/main/src/binfhe/examples/eval-function.cpp)

**Comment by arcturusannamalai** [comment]
I think there is some more work to be done; I'm not able to get to this yet.
