### ISSUE TITLE
Missing documentation for parameters?

### ISSUE THREAD

**Issue by yav** [openfheorg/openfhe-python#97]
I can't seem to find any documentation in here https://openfheorg.github.io/openfhe-python/html/cryptocontext.html, about the parameter creation functions `CCParamsBFVRNS` and friends.   The source code is easy enough to follow so not a blocker, but it'd be nice to add them to the docs.

**Comment by arcturusannamalai** [comment]
Seems like we need to introduce parametrized docs for the code

```
template <typename T>
void bind_parameters(py::module &m,const std::string name)
```
in file 
```
openfhe-python/src/lib/bindings.cpp
```

**Comment by arcturusannamalai** [comment]
actually the solution seems simple to just add whats already available without adding more doc
![Uploading Screenshot 2024-04-28 at 2.42.04 PM.png…]()

**Comment by arcturusannamalai** [comment]
updated PR @yspolyakov - https://github.com/openfheorg/openfhe-python/pull/143
